volumes:
  db-store:
  psysh-store: # thinker用

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/dev/container/backend/Dockerfile
    volumes:
      - type: bind
        source: ./proto/nlp.proto
        target: /backend/resources/proto/nlp.proto
      - type: bind
        source: ./backend
        target: /backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    depends_on:
      - "db"
      - "redis"
    ports:
      - "2010:2010"
    environment:
      - APP_NAME=かどで日記3
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=${APP_URL:-http://localhost:2010}
      - LOG_CHANNEL=single
      - LOG_LEVEL=debug
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-db}
      - DB_DATABASE=${DB_DATABASE:-kadode_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@usuyuki.net
      - MAIL_FROM_NAME=かどで日記
      - LOG_SLACK_LEVEL=error
      - GOOGLE_APPLICATION_CREDENTIALS={$GOOGLE_APPLICATION_CREDENTIALS}
      - GCS_PACKET={$GCS_PACKET}
      - BACKUP_NOTIFICATION_EMAIL_TO={$BACKUP_NOTIFICATION_EMAIL_TO}
      - SERVER_BACKUP_PATH={$SERVER_BACKUP_PATH}
      - GRPC_SERVER_URL=nlp:2020

  nlp:
    build:
      context: ./nlp
      dockerfile: ../infra/dev/container/nlp/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./nlp
        target: /nlp
      - type: bind
        source: ./proto/nlp.proto
        target: /nlp/proto/nlp.proto
    depends_on:
      - "db"
    environment:
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-db}
      - DB_DATABASE=${DB_NAME:-kadode_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/dev/container/frontend/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "2000:2000"
    user: "1000:1000"
    volumes:
      - ./frontend:/frontend
    # command: sh -c "pnpm install"

  db: # 3306 port
    build:
      context: ./infra/dev/container/mysql
      dockerfile: Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - ./infra/dev/container/mysql/initial:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-kadode_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  redis: # 6379 port
    image: "redis:alpine"
    volumes:
      - "./data/redis:/data"
      - "./infra/dev/container/redis/redis.conf:/etc/redis.conf"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:${DB_PORT:-3306}
      - PMA_USER=${DB_USER:-phper}
      - PMA_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - "db"
    ports:
      - 7010:80
    volumes:
      - ./infra/dev/container/phpmyadmin/sessions:/sessions

  mail:
    image: mailhog/mailhog
    ports:
      - 7011:8025

  selenium:
    build:
      context: ./infra/dev/container/selenium
      dockerfile: Dockerfile
    tty: true
    ports:
      - 4444:4444
      - 5900:5900
    privileged: true
