volumes:
  db-store:

# dc -f compose-prod.yml up -d --build

services:
  backend:
    build:
      context: .
      dockerfile: ./infra/prod/php/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./backend/storage
        target: /work/backend/storage
    environment:
      - APP_NAME=かどで日記3
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost:2010}
      - LOG_CHANNEL=single
      - LOG_LEVEL=debug
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-db}
      - DB_DATABASE=${DB_DATABASE:-kadode_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@usuyuki.net
      - MAIL_FROM_NAME=かどで日記
      - LOG_SLACK_LEVEL=error
      - GOOGLE_APPLICATION_CREDENTIALS={$GOOGLE_APPLICATION_CREDENTIALS}
      - GCS_PACKET={$GCS_PACKET}
      - BACKUP_NOTIFICATION_EMAIL_TO={$BACKUP_NOTIFICATION_EMAIL_TO}
      - SERVER_BACKUP_PATH={$SERVER_BACKUP_PATH}

  nlp:
    build:
      context: .
      dockerfile: ./infra/prod/python/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./nlp
        target: /nlp
      - type: bind
        source: ./proto/nlp.proto
        target: /nlp/proto/nlp.proto
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-kadode_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  frontend:
    build:
      context: .
      dockerfile: ./infra/prod/node/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "2000:2000"
    user: "1000:1000"
    # command: sh -c "pnpm install"

  nginx:
    build:
      context: .
      dockerfile: ./infra/prod/nginx/Dockerfile
    ports:
      - "2010:2010"
    depends_on:
      - "backend"
      - "frontend"
    volumes:
      - type: bind
        source: ./backend
        target: /work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/prod/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - ./infra/prod/mysql/initial:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-kadode_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - "backend"
      - "nlp"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./infra/prod/redis/redis.conf:/etc/redis.conf"
