version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  backend:
    build:
      context: .
      dockerfile: ./infra/dev/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-kadode_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  frontend:
    build:
      context: .
      dockerfile: ./infra/dev/node/Dockerfile
    tty: true
    volumes:
      - ./frontend:/frontend
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn install && yarn dev"

  nginx:
    build:
      context: .
      dockerfile: ./infra/dev/nginx/Dockerfile
    ports:
      - "7001:80"
      - "7000:3000"
    depends_on:
      - "backend"
      - "frontend"
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/dev/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - ./infra/dev/mysql/initial:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-kadode_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./infra/dev/redis/redis.conf:/etc/redis.conf"

  # schemaspy:
  #   image: schemaspy/schemaspy
  #   volumes:
  #     - ./infra/dev/schemaspy/output:/output
  #     - ./infra/dev/schemaspy/drivers:/drivers
  #   command: >
  #     java -jar schemaspy.jar
  #     -t mysql
  #     -dp /drivers
  #     -host db
  #     -port 3306
  #     -db ${DB_NAME:-kadode_local}
  #     -u ${DB_USER:-phper}
  #     -p ${DB_PASS:-secret}
  #     -s ${DB_NAME:-kadode_local}
  #     -connprops allowPublicKeyRetrieval\\=false useSSL\\=false

  # schemaspy_web:
  #   image: nginx:1.18-alpine
  #   volumes:
  #     - ./infra/dev/schemaspy/output:/usr/share/nginx/html
  #   ports:
  #     - ${SCHEMASPY_WEB_PORT:-8080}:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:${DB_PORT:-3306}
      - PMA_USER=${DB_USER:-phper}
      - PMA_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - db
    ports:
      - 7010:80
    volumes:
      - ./infra/dev/phpmyadmin/sessions:/sessions
  mail:
    image: mailhog/mailhog
    ports:
      - 7011:8025

  selenium:
    build:
      context: .
      dockerfile: ./infra/dev/selenium/Dockerfile
    tty: true
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - nginx
    privileged: true
