# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import nlp_pb2 as proto_dot_nlp__pb2


class NlpManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAll = channel.unary_unary(
                '/nlp.NlpManager/GenerateAll',
                request_serializer=proto_dot_nlp__pb2.GenerateAllRequest.SerializeToString,
                response_deserializer=proto_dot_nlp__pb2.GenerateAllResponse.FromString,
                )


class NlpManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAll,
                    request_deserializer=proto_dot_nlp__pb2.GenerateAllRequest.FromString,
                    response_serializer=proto_dot_nlp__pb2.GenerateAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.NlpManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NlpManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.NlpManager/GenerateAll',
            proto_dot_nlp__pb2.GenerateAllRequest.SerializeToString,
            proto_dot_nlp__pb2.GenerateAllResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
