openapi: 3.0.3
info:
  title: かどで日記バッグエンドAPI
  description: かどで日記の基幹となるバックエンドAPI
  version: 1.0.0
servers:
  - url: "https://api.kado.day/api/v1"
    description: 本番API
  - url: "https://localhost:2010/api/v1"
    description: ローカルAPI
paths:
  $ref: ./_paths.yaml
components:
  $ref: ./_components.yml

  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: kadode_nikki3_session
    requestedWith:
      type: apiKey
      in: header
      name: X-Requested-With

security:
  - requestedWith: []
