apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kadode-prod
spec:
  selector:
    app: backend-app
  ports:
    - name: http
      port: 2010
      targetPort: 2010
  type: LoadBalancer # 外部に公開するために、ServiceのtypeをLoadBalancerに指定します
