apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: kadode-prod
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: ghcr.io/kadodeproject/kadode_nikki3_frontend:latest
          ports:
            - containerPort: 2000 # ここにfrontendアプリケーションが使用するポート番号を指定します
          envFrom:
            - configMapRef:
                name: frontend-config
          imagePullPolicy: Always # 常に最新のイメージを使用するように指定します
