apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kadode-prod
spec:
  selector:
    app: frontend-app
  ports:
    - name: http
      port: 2000 # frontendアプリケーションが使用するポート番号を指定します
      targetPort: 2000
  type: LoadBalancer # 外部に公開するために、ServiceのtypeをLoadBalancerに指定します
