apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kadode-prod
data:
  MYSQL_ROOT_PASSWORD: "example"
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "kadode_production"
  MYSQL_USER: "phper"
  MYSQL_PASSWORD: "secret"
