<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp.proto

namespace GrpcClient\Nlp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *client streaming
 *
 * Generated from protobuf message <code>nlp.GenerateAllResponse</code>
 */
class GenerateAllResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool start = 1;</code>
     */
    protected $start = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $start
     * }
     */
    public function __construct($data = NULL) {
        \GrpcClient\GPBMetadata\Nlp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool start = 1;</code>
     * @return bool
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>bool start = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkBool($var);
        $this->start = $var;

        return $this;
    }

}

