name: コンテナ生成とデプロイ

on: [pull_request]
# on:
#   pull_request:
#     branches:
#       - main
#       - develop/k8s対応
#     types: [closed]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: ["frontend", "backend", "nlp"]
        # redisは外の物を使うのでOK

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USUYUKI_GITHUB_TOKEN }}

      # arm64とamd64両対応のため
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.name }}
          file: ./infra/prod/container/${{ matrix.name }}/Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/kadodeproject/kadode_nikki3_${{ matrix.name }}:${{ github.sha }}
            ghcr.io/kadodeproject/kadode_nikki3_${{ matrix.name }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

        # 現状まだキャッシュ自動削除の仕組みができていないらしい→https://docs.docker.com/build/ci/github-actions/cache/
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  # deploy:
  #   name: Deploy to Server
  #   needs: push_to_registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         port: ${{ secrets.SERVER_PORT }}
  #         script: |
  #           cd ${{ secrets.BLOG_SERVER_PATH }}
  #           git checkout main
  #           git pull origin main
  #           # latestだと更新できないので、shaの方で更新をかける
  #           kubectl rolling-update frontend --image=ghcr.io/kadodeproject/kadode_nikki3_frontend:${{ github.sha }}
