name: 【backend】テスト[結合]

on:
  pull_request:
    branches: [main]
    paths:
      - backend/**

# working-directoryの指定だとapkで止まるので指定せず必要に応じてcdする

jobs:
  phpunit-combined:
    name: PHPUnit combined test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
    container:
      image: php:8.2-cli-alpine
    steps:
      - name: apk install
        run: |
          apk add libzip-dev

      #  phpのためにbcmathとzip
      - name: add extention
        run: docker-php-ext-install bcmath zip pdo_mysql

      - uses: actions/checkout@v3

      - name: cache composer.phar
        id: cache-composer-phar
        uses: actions/cache@v3
        with:
          path: ./backend/composer.phar
          # composerのバージョンになりそうなものがないのでcomposer.lockのハッシュで代用
          key: backend-composer-phar-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            backend-composer-phar-

      - name: Install Composer itself
        if: steps.cache-composer-phar.outputs.cache-hit != 'true'
        run: |
          cd backend
          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
          then
              >&2 echo 'ERROR: Invalid installer checksum'
              rm composer-setup.php
              exit 1
          fi
          php composer-setup.php --quiet
          RESULT=$?
          rm composer-setup.php
          exit $RESULT

      - name: cache composer vendor
        id: cache-composer-vendor
        uses: actions/cache@v3
        with:
          path: ./backend/vendor
          key: backend-composer-vendor-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            backend-composer-vendor-

      # -qオプション消すと短くはなるけど、結構な頻度でcomposer install失敗するのでいつでも見れるように短くなるオプション消す
      - name: Composer install
        if: steps.cache-composer-vendor.outputs.cache-hit != 'true'
        run: |
          cd backend
          php composer.phar install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # - name: Show databases for root user
      #   run: mysql --protocol=tcp -h  mysql -P 3306 -u root -ppassword -e "SHOW DATABASES"
      # combined testのため多めに設定が必要
      - name: setup laravel
        run: |
          cd backend
          cp .env.ci .env
          php artisan migrate

      #テスト
      - name: combined test
        run: |
          cd backend
          ./vendor/bin/phpunit --testsuite MinimumOperationCheck --testsuite Feature --testdox
