name: 【backend】PHPテスト[結合]

on:
  pull_request:
    branches: [main]
    paths:
      - backend/**

jobs:
  laravel_test:
    name: phpunit combined test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          # ini-values: extension="redis.so"
          # 二重で読み込まれるため上記のphp.ini記述処理は不要
          extensions: redis

      - name: cache vendor
        id: cache_vendor
        uses: actions/cache@v3
        with:
          path: ./backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: copy .env for ci
        run: cp backend/.env.ci backend/.env

      #ライブラリインストール
      #PHP
      - name: composer install
        if: steps.cache_vendor.outputs.cache-hit != 'true'
        run: cd backend && composer install -n --prefer-dist

      #Laravel初期構築
      - name: composer dump autoload
        run: cd backend && composer dump-autoload
      - name: generate key
        run: cd backend && php artisan key:generate --env=testing
      - name: migrate
        run: cd backend && php artisan migrate
      #テスト
      - name: unit test
        run: cd backend && ./vendor/bin/phpunit --testsuite MinimumOperationCheck --testsuite Feature --testdox
