name: 【backend】静的解析
on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

# working-directoryの指定だとapkで止まるので指定せず必要に応じてcdする

jobs:
  phpstan:
    name: PHPStan with Larastan
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli-alpine
    steps:
      - name: apk install
        run: |
          apk add libzip-dev

      #  phpのためにbcmathとzip
      - name: add extention
        run: docker-php-ext-install bcmath zip

      - uses: actions/checkout@v3

      - name: cache composer.phar
        id: cache-composer-phar
        uses: actions/cache@v3
        with:
          path: ./backend/composer.phar
          # composerのバージョンになりそうなものがないのでcomposer.lockのハッシュで代用
          key: backend-composer-phar-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            backend-composer-phar-

      - name: Install Composer itself
        if: steps.cache-composer-phar.outputs.cache-hit != 'true'
        run: |
          cd backend
          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
          then
              >&2 echo 'ERROR: Invalid installer checksum'
              rm composer-setup.php
              exit 1
          fi
          php composer-setup.php --quiet
          RESULT=$?
          rm composer-setup.php
          exit $RESULT

      - name: cache composer vendor
        id: cache-composer-vendor
        uses: actions/cache@v3
        with:
          path: ./backend/vendor
          key: backend-composer-vendor-${{ hashfiles('**/composer.lock') }}
          restore-keys: |
            backend-composer-vendor-

      # -qオプション消すと短くはなるけど、結構な頻度でcomposer install失敗するのでいつでも見れるように短くなるオプション消す
      - name: Composer install
        if: steps.cache-composer-vendor.outputs.cache-hit != 'true'
        run: |
          cd backend
          php composer.phar install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHPStan
        run: |
          cd backend
          # ciのスペックではシングルスレッドで走らせたほうが早いので設定を置き換えする
          # sed -i '/parameters:/a\ \tparallel:\n\t\tmaximumNumberOfProcesses: 1' phpstan.neon
          ./vendor/bin/phpstan analyse --no-progress --memory-limit=4G --error-format=github
