name: 【frontend】統合(E2E)テスト

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  frontend_integration_test:
    name: Playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # global cacheの cache
          cache: "pnpm"
          cache-dependency-path: |
            frontend/pnpm-lock.yaml

      # node_modelusはキャッシュしてくれないっぽいので自分でやる
      - name: cache node_modelus
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: frontend-node-modules-${{ hashfiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            frontend-node-modules-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: svelte sync
        run: pnpm prepare

      - name: integration test
        run: pnpm test:i
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
